name: strongmotion-database
channels:
- conda-forge
- defaults
dependencies:
- amptools
- jupyter
- lxml
- matplotlib
- numpy
- obspy
- pandas
- pytest
- pytest-cov
- python=3.5
- xlrd
- xlwt
- openpyxl
- obspy
- xlsxwrite
